[package]
name = "rsqc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.5.21",features = ["derive"] }
serde = {version="1.0.215",features=["serde_derive"]}
tera = {version="1.20.0"}
